experimental-features = nix-command flakes
sandbox = false
build-users-group =
require-sigs = true
substituters = https://cache.nixos.org/
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
